language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest tests
  - black --check sranodec/ tests/
  - isort -rc --check-only -vb sranodec/*.py tests/*.py
